### ISSUE TITLE
tree-sitter-pioasm seems to fail silently in `helix`

### ISSUE THREAD

**Issue by crabdancing** [leo60228/tree-sitter-pioasm#2]
When setting this up, `.pio` / `.pioasm` files on Helix end up having no syntax highlighting. I'm not sure why. :/ Was wondering if you had any ideas?

## Setup:

In Helix's languages.toml (in the project root):
```toml
[[language]]
name = "pioasm"
scope = "source.pioasm"
file-types = ["pio", "pioasm"]
indent = { tab-width = 4, unit = " " }
comment-tokens = ";"

[[grammar]]
name = "pioasm"
source = { git = "https://github.com/leo60228/tree-sitter-pioasm", rev = "afece58efdb30440bddd151ef1347fa8d6f744a9" }
```

Then built Helix from source. I saw `tree-sitter-pioasm` get pulled, and later found its `.so` in my runtime dir -- so it's definitely building correctly. 

```
helix 25.01.1 (fe03376a)
```
